version: "3.4"
volumes:
 dbdata:

services:
 mysql:
  image: mysql:latest
  container_name: mysql
  volumes:
      - ${MYSQL_DB}:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    MYSQL_USER: "${MYSQL_USER}"
    MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  ports:
    - "3306:33061"

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links: 
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_PORTS: 3300
  ports: 
    - "8080:80"
